apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "gethDeploymentName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "gethDeploymentName" . }}
spec:
  selector:
    matchLabels:
      app: {{ template "gethDeploymentName" . }}
{{ toYaml .Values.geth.updateStrategy | indent 2 }}
  template:
    metadata:
      labels:
        app: {{ template "gethDeploymentName" . }}
        tags.datadoghq.com/env: development
        tags.datadoghq.com/version: "0.0.1"
        tags.datadoghq.com/service: {{ template "gethDeploymentName" . }}
        admission.datadoghq.com/enabled: "true"
    spec:
      # serviceAccountName: {{ .Values.geth.serviceAccountName }}
{{- if .Values.geth.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.geth.nodeSelector | indent 8 }}
{{- end }}
{{- $secretName := .Values.common.secret.name }}
      initContainers:
        - name: preboot
          image: {{ .Values.images.prysm.name }}:{{ .Values.images.prysm.tag }}
          imagePullPolicy: Always
          command:
            - "/bin/bash"
          args:
            - "-c"
            - "sleep 300"
          env:
{{- if .Values.geth.env }}
{{- range $k, $v := .Values.geth.env }}
            - name: {{ $k }}
              value: {{ $v }}
{{- end }}
{{- end }}
          {{- range $k, $v := .Values.common.secret.values }}
            - name: {{ template "formatEnvVarName" $k }}
              valueFrom:
                secretKeyRef:
                  key: {{ $k }}
                  name: {{ $secretName}}
          {{- end }}
{{- if .Values.geth.volumeMounts }}
          volumeMounts:
{{ toYaml .Values.geth.volumeMounts | indent 12 }}
{{- end}}
        - name: init-execution
          image: {{ .Values.images.prysm.name }}:{{ .Values.images.prysm.tag }}
          imagePullPolicy: Always
          command:
            - "/layr-devnet/execution/initGenesis.sh"
          env:
{{- if .Values.geth.env }}
{{- range $k, $v := .Values.geth.env }}
            - name: {{ $k }}
              value: {{ $v }}
{{- end }}
{{- end }}
          {{- range $k, $v := .Values.common.secret.values }}
            - name: {{ template "formatEnvVarName" $k }}
              valueFrom:
                secretKeyRef:
                  key: {{ $k }}
                  name: {{ $secretName}}
          {{- end }}
{{- if .Values.geth.volumeMounts }}
          volumeMounts:
{{ toYaml .Values.geth.volumeMounts | indent 12 }}
{{- end}}
      containers:
        - name: geth
          image: {{ .Values.images.geth.name }}:{{ .Values.images.geth.tag }}
          imagePullPolicy: Always
          command:
            - "/layr-devnet/execution/start.sh"
          env:
{{- if .Values.geth.env }}
{{- range $k, $v := .Values.geth.env }}
            - name: {{ $k }}
              value: {{ $v }}
{{- end }}
{{- end }}
          {{- range $k, $v := .Values.common.secret.values }}
            - name: {{ template "formatEnvVarName" $k }}
              valueFrom:
                secretKeyRef:
                  key: {{ $k }}
                  name: {{ $secretName}}
          {{- end -}}
{{- if .Values.geth.volumeMounts }}
          volumeMounts:
{{ toYaml .Values.geth.volumeMounts | indent 12 }}
{{- end}}
{{- if .Values.geth.resources }}
          resources:
{{ toYaml .Values.geth.resources | indent 12 }}
{{- end}}
          ports:
{{- if .Values.geth.ports }}
{{- range $k, $v := .Values.geth.ports }}
            - containerPort: {{ $v.containerPort }}
              name: {{ $v.name }}
              protocol: {{ $v.protocol }}
{{- end }}
{{- end }}
{{- if .Values.geth.volumes }}
      volumes:
{{ toYaml .Values.geth.volumes | indent 8 }}
{{- end}}
