apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ template "validatorName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "validatorName" . }}
spec:
  serviceName: {{ template "validatorName" . }}
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "validatorName" . }}
  template:
    metadata:
      labels:
        app: {{ template "validatorName" . }}
        tags.datadoghq.com/env: development
        tags.datadoghq.com/version: "0.0.1"
        tags.datadoghq.com/service: {{ template "validatorName" . }}
        admission.datadoghq.com/enabled: "true"
    spec:
      # serviceAccountName: {{ .Values.validator.serviceAccountName }}
{{- if .Values.validator.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.validator.nodeSelector | indent 8 }}
{{- end }}
{{- $secretName := .Values.common.secret.name }}
      initContainers:
        - name: wait-for-beacon
          image: {{ .Values.images.prysm.name }}:{{ .Values.images.prysm.tag }}
          imagePullPolicy: Always
          command: ["/bin/bash"]
          args:
              - "-c"
              - "sleep 30"
      containers:
        - name: validator
          image: {{ .Values.images.prysm.name }}:{{ .Values.images.prysm.tag }}
          imagePullPolicy: Always
          command:
            - "/layr-devnet/validator/start.sh"
          env:
{{- if .Values.validator.env }}
{{- range $k, $v := .Values.validator.env }}
            - name: {{ $k }}
              value: '{{ $v }}'
{{- end }}
{{- end }}
          {{- range $k, $v := .Values.common.secret.values }}
            - name: {{ template "formatEnvVarName" $k }}
              valueFrom:
                secretKeyRef:
                  key: {{ $k }}
                  name: {{ $secretName}}
          {{- end -}}
{{- if .Values.validator.volumeMounts }}
          volumeMounts:
{{ toYaml .Values.validator.volumeMounts | indent 12 }}
{{- end}}
{{- if .Values.validator.resources }}
          resources:
{{ toYaml .Values.validator.resources | indent 12 }}
{{- end}}
          ports:
{{- if .Values.validator.ports }}
{{- range $k, $v := .Values.validator.ports }}
            - containerPort: {{ $v.containerPort }}
              name: {{ $v.name }}
              protocol: {{ $v.protocol }}
{{- end }}
{{- end }}
{{- if .Values.validator.volumes }}
      volumes:
{{ toYaml .Values.validator.volumes | indent 8 }}
{{- end}}
  volumeClaimTemplates:
    - metadata:
        name: validator-data
      spec:
        accessModes:
          - ReadWriteMany
        storageClassName: efs
        resources:
          requests:
            storage: 10Gi
